### ISSUE TITLE
Build failure on GHC 8.6.5

### ISSUE THREAD

**Issue by TikhonJelvis** [TikhonJelvis/modular-arithmetic#19]
The package builds fine on GHC 8.8.4, but fails on 8.6.5 with the following error:

```
src/Data/Modular.hs:296:12: error:
    • Couldn't match type ‘p’ with ‘Proxy’
      Expected type: Proxy n
        Actual type: p n
    • When checking that the pattern signature: p n
        fits the type of its context: Proxy n
      In the pattern: _ :: p n
      In the pattern: SomeNat (_ :: p n)
    |
296 |   SomeNat (_ :: p n) <- someNatVal n
    |            ^^^^^^^^
```

**Comment by TikhonJelvis** [comment]
My theory is that this is related to the following change introduced in GHC 8.8.1:

> ScopedTypeVariables: The type variable that a type signature on a pattern can bring into scope can now stand for arbitrary types. Previously, they could only stand in for other type variables, but this restriction was deemed unnecessary in [GHC proposal #29][29]. Also see [Trac #15050][trac].

[29]: https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0029-scoped-type-variables-types.rst
[trac]: https://ghc.haskell.org/trac/ghc/ticket/15050

Regardless, seems like the easiest solution would be replacing `:: p n` with `:: Proxy n`.

**Comment by TikhonJelvis** [comment]
Okay, should be fixed with `modular-arithmetic-2.0.0.1`. I'll make `modular-arithmetic-2.0.0.0` as deprecated.
