### PR TITLE
Fix for 9.2+

### PR DESCRIPTION
**Pull request by cydparser**
I've verified that this change builds using GHC 8.10.7, 9.0.2, and 9.2.4.

The doctests only pass for me on 9.2.4, but that might be due to how I'm using Nix. It appears that _doctest_ cannot see _typelits-witnesses_.

```
cabal repl test:examples

λ :show packages
active package flags:
  -package-id typelits-witnesses-0.4.0.0-5eCXrhtGP6h57ytsIr2YQw
  -package-id doctest-0.20.0-LibhKUW41H15QzzuYGnY3a
  -package-id base-4.14.3.0

λ :l src/Data/Modular.hs
[1 of 1] Compiling Data.Modular     ( src/Data/Modular.hs, interpreted )
Ok, one module loaded.

λ import Test.DocTest (doctest)
λ doctest ["src/Data/Modular.hs"]

src/Data/Modular.hs:44:1: error:
    Could not find module ‘GHC.TypeLits.Compare’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

### CODE REVIEW

**Comment by TikhonJelvis** [comment]
Sweet, thanks for the PR! I can cut a release tomorrow. I'll also poke around and see what's up with the tests; maybe flakify the Nix config for the repo too...

**Comment by TikhonJelvis** [comment]
I converted the repo to flakes, which also fixed the problem with the doctests so they ran fine on 8.10.7 and 9.0.2. I also added basic CI.

Could you merge in `master` and add 9.2.4 to `flake.nix`? The build and tests should work correctly after that. Alternatively, I can make those changes if you let me push to the branch for this PR—I think there's a checkbox or something in GitHub to allow that.

Thanks!

**Comment by cydparser** [comment]
I've rebased. I don't see the option to allow contributors to modify the PR.

**Comment by TikhonJelvis** [comment]
Sweet, thanks! Looks good, I'll merge it when the CI run finishes.

**Comment by TikhonJelvis** [comment]
Oh, wait, we need to add 9.2.4 to the CI config too. There's probably a way to automate that, but I can't think of it off-hand :/

**Comment by TikhonJelvis** [comment]
[This is the GitHub feature I was thinking of][1], but I'm not sure whether it's available by default/etc.

[1]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by TikhonJelvis** [comment]
Thanks for the fix! Just published [version 2.0.0.2][1] with these changes.

[1]: https://hackage.haskell.org/package/modular-arithmetic-2.0.0.2

**Comment by cydparser** [comment]
Ah, that feature might not be available since the PR is from an organization rather than a personal fork.

**Comment by TikhonJelvis** [comment]
Yeah, makes sense, modern UIs work in mysterious ways :P

Also cool to see a company using Haskell!
