### ISSUE TITLE
Support for GHC 7.8.2

### ISSUE THREAD

**Issue by peti** [TikhonJelvis/modular-arithmetic#2]
I noticed that this package won't compile with GHC 7.8.2. It appears that some of the constructors have disappeared from the latest version of `base`:

```
src/Data/Modular.hs:65:36:
    Not in scope: type constructor or class ‘SingI’

src/Data/Modular.hs:66:30: Not in scope: ‘fromSing’
```

Is there any chance that a new version of this package could be release to Hackage that remedies these errors?
